model = "gpt-5.1-codex-max"
# notify = [
#   "uv",
#   "run",
#   "--isolated",
#   "--no-project",
#   "--python",
#   "3.14",
#   "python3",
#   "/Users/adam/.codex/notify.py",
# ]
sandbox_mode = "workspace-write"
approval_policy = "on-request"
model_reasoning_effort = "high"

[features]
web_search_request = true

[sandbox_workspace_write]
network_access = true
writable_roots = [
  "/Users/adam/.cache/gh",
  "/Users/adam/.cache/uv",
  "/Users/adam/.cargo",
  "/Users/adam/.npm",
  "/Users/adam/.rustup",
  "/Users/adam/Library/Caches/Homebrew",
  "/Users/adam/Library/Caches/mise",
]

[tui]
notifications = true

[mcp_servers.sosumi]
url = "https://sosumi.ai/mcp"
# command = "pnpm"
# args = ["dlx", "mcp-remote", "https://sosumi.ai/mcp"]
# args = ["dlx", "mcp-remote", "http://localhost:8787/mcp"]

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true
